import financial from "../assets/img/financial.jpg";
import science from "../assets/img/science.jpeg";
import environment from "../assets/img/environment.avif";
import ai from "../assets/img/ai.jpeg";

const api = [
  {
    id: 1,
    title: "بازاڕە جیهانیەکان بەهێز بوون بەهۆی هیوای ئابووری",
    description: "بازاڕەکان لە جیهاندا بەهێز بوون بەهۆی پێشبینی گەشەی ئابووری.",
    author: "نووسەر: Jane Smith",
    date: "2025-11-26",
    category: "دارایی",
    image: financial,
  },
  {
    id: 2,
    title: "پێشکەوتن لە تێکنەلۆجی وزەی نوێ",
    description: "زانایان پەناڵی خۆرەی نوێ دروست کردووە کە ٣٠٪ زۆرتر کاریگەرە.",
    author: "نووسەر: John Doe",
    date: "2025-11-25",
    category: "زانست",
    image: science,
  },
  {
    id: 3,
    title: "کۆمەڵگەی ناوخۆی دەستپێکرد بە پڕۆژەی سەوز",
    description:
      "خەڵکی سپرینگفیلد دەستپێکردن بە دانانی ١٠٠٠٠ دارستان لە ساڵێکدا.",
    author: "نووسەر: Emily Johnson",
    date: "2025-11-24",
    category: "ژینگە",
    image: environment,
  },
  {
    id: 4,
    title: "کۆمپانیا گەورەکان هاوکاری AI دەستپێکرد",
    description:
      "کۆمپانیا گەورەکان هاوکارییان کرد بۆ پەرەپێدانی ستانداردی ئاخلاقی AI.",
    author: "نووسەر: Michael Brown",
    date: "2025-11-23",
    category: "تێکنەلۆجی",
    image: ai,
  },
  {
    id: 5,
    title: "ڕێکەوتنی ئاشتیی مێژوویی واژوو کرا",
    description:
      "دوو وڵات ڕێکەوتنی ئاشتیی مێژوویی واژوو کرد بۆ کۆتایی هێنان بە شەڕی چەندین ساڵە.",
    author: "نووسەر: Sarah Lee",
    date: "2025-11-22",
    category: "جیهان",
    image: financial,
  },
  {
    id: 6,
    title: "توێژینەوەی نوێ سوودەکانی مێدیتەیشن دەردەخاتەوە",
    description:
      "توێژینەوە نوێ دەردەخاتەوە کە مێدیتەیشن ڕۆژانە دەتوانێت سترێس کەم بکات و تەندروستی باشتر بکات.",
    author: "نووسەر: David Clark",
    date: "2025-11-21",
    category: "تەندروستی",
    image: science,
  },
  {
    id: 7,
    title: "تیمێکی وەرزشی پسپۆڕی بردەوە دوای ٢٠ ساڵ",
    description:
      "تایگەرز یەکەم قهرمانییان بردەوە دوای دوو دەیە لە یارییەکی سەرنجڕاکێشدا.",
    author: "نووسەر: Laura Martinez",
    date: "2025-11-20",
    category: "وەرزش",
    image: environment,
  },
  {
    id: 8,
    title: "پێشکەوتنە گەورەکان لە تێکۆشانی ئاسمانی",
    description:
      "ناسا پلانەکانی بۆ گەشتێکی نوێ بۆ لێکۆڵینەوەی سیارەی دوور ڕوون کرد.",
    author: "نووسەر: Robert Wilson",
    date: "2025-11-19",
    category: "زانست",
    image: ai,
  },
  {
    id: 9,
    title: "پیشەسازی فەشەن بە مادەی سەوز دەستپێ دەکات",
    description:
      "براندە گەورەکان مادە سازگار بە ژینگە و شێوازە ئاخلاقیەکان بەکار دەهێنن.",
    author: "نووسەر: Sophia Taylor",
    date: "2025-11-18",
    category: "ژینگەی ژیان",
    image: financial,
  },
  {
    id: 10,
    title: "ئاگاداری سەلامەتی ئینتەرنێت: مەترسی نوێ دەردەکەوێت",
    description:
      "پەروەردەکاران ئاگاداری دەدەن لەسەر هێرشێکی زۆر پێشکەوتوو بۆ بانکی جیهانی.",
    author: "نووسەر: Chris Evans",
    date: "2025-11-17",
    category: "تێکنەلۆجی",
    image: science,
  },

  // --- Generated items 11 to 100 ---
  {
    id: 11,
    title: "هاوبەشی کارامەیی لە بازاڕەکانی نێوان وڵاتان",
    description:
      "ڕاپۆرتێکی نوێ دەربارەی هاوبەشی کارامەیی و گواستنەوەی سەودا بڵاوکرایەوە.",
    author: "نووسەر: Amina Hassan",
    date: "2025-11-16",
    category: "دارایی",
    image: environment,
  },
  {
    id: 12,
    title: "چیپەکان بەکارەهێنانی وزە کەم دەکەن",
    description:
      "توێژینەوەکانی ناو لابراتوارەکان دەردەخاتەوە چیپە نوێکان وزەی کەمتر دەخۆن.",
    author: "نووسەر: Omar Khalid",
    date: "2025-11-15",
    category: "زانست",
    image: ai,
  },
  {
    id: 13,
    title: "خاڵی سەوزی شارەکان زیاد کرا",
    description:
      "پڕۆژەی پارک و دارستان لە شارە گەورەکان دەستپێکرد بۆ باشکردنی ژینگە.",
    author: "نووسەر: Noor Ali",
    date: "2025-11-14",
    category: "ژینگە",
    image: financial,
  },
  {
    id: 14,
    title: "ڕێنمایی نوێ بۆ ئاخلاقیاتی AI بڵاوکراوە",
    description:
      "هاوپەیمانەکانی بازرگانی یاسای سەلماندن بۆ مودێلی AI دەستنیشان کرد.",
    author: "نووسەر: Daniel Park",
    date: "2025-11-13",
    category: "تێکنەلۆجی",
    image: science,
  },
  {
    id: 15,
    title: "گۆڕانکاری سیاسییەکان کاریگەرییان هەیە لە نرخی بازاڕ",
    description:
      "بەرهەمی بەرزبوونەوەی هەواڵی سیاسی لە رووداوە گەورەکاندا لێکۆڵینەوە کرا.",
    author: "نووسەر: Fatima Rahman",
    date: "2025-11-12",
    category: "جیهان",
    image: environment,
  },
  {
    id: 16,
    title: "ڕاهێنانی خاوێنی ڕۆژانە بۆ کەمکردنی سترێس",
    description:
      "پەروەردەی تەندروستی ڕێنماییەکی سادە بۆ مێدیتەیشن و نەفەسگرتن دابین کرد.",
    author: "نووسەر: Ethan Walker",
    date: "2025-11-11",
    category: "تەندروستی",
    image: ai,
  },
  {
    id: 17,
    title: "ڕیکوردی نوێ لە یارییەکانی گۆڵ بەدەست هات",
    description: "تیمێکی ناوەندی توانست لە پەیوەندیدا ریکوردی گۆڵ توماربکات.",
    author: "نووسەر: Sofia Gomez",
    date: "2025-11-10",
    category: "وەرزش",
    image: financial,
  },
  {
    id: 18,
    title: "ڕاکێشانی فیزیای ئاسمانی لە سیارەی دوور",
    description:
      "تێکۆشەران شێوەی خۆرەناسیی گۆڕانکاری لە جوگرافیای سیارەیەک نیشاندەن.",
    author: "نووسەر: Liam Carter",
    date: "2025-11-09",
    category: "زانست",
    image: science,
  },
  {
    id: 19,
    title: "هاوپەیمانی فەشەن بۆ بهێشتنی پاشەکەوتی ژینگە",
    description: "کارگێرییەکانی کەمکردنی خەرجی و مادەی ناسازگار پێشکەش کرا.",
    author: "نووسەر: Layla Noor",
    date: "2025-11-08",
    category: "ژینگەی ژیان",
    image: environment,
  },
  {
    id: 20,
    title: "چاوەڕوانی هێرشەکانی سەلامەتی دیجیتاڵی",
    description:
      "ئەرکدارانی سێکیوریتی هەڵسەنگاندنی نوێیان بۆ پاراستنی بانکی دیژیتال کرد.",
    author: "نووسەر: Oliver Stone",
    date: "2025-11-07",
    category: "تێکنەلۆجی",
    image: ai,
  },
  {
    id: 21,
    title: "بازاڕی هەژماری گشتی ڕاوەستاوی کەم کرد",
    description:
      "قەدەغەی نوێ لەسەر قەرزکردن کاریگەری هەبوو لە بەرزبوونەوەی نرخەکان.",
    author: "نووسەر: Maryam Aziz",
    date: "2025-11-06",
    category: "دارایی",
    image: financial,
  },
  {
    id: 22,
    title: "لەبارەی بۆتانی ڕەنگاوی توێژینەوەیەکی نوێ بڵاوکراوە",
    description:
      "زانیارییەکی گرنگ سەبارەی یاسای ڕەنگاوی لە گیانەوەکان بۆ ناو زانست هات.",
    author: "نووسەر: Zain Abbas",
    date: "2025-11-05",
    category: "زانست",
    image: science,
  },
  {
    id: 23,
    title: "پاراستنی ئاوی ڕووباری گەورە بە پڕۆژەی هاوبەش",
    description:
      "خەڵکی ناوچە هاوبەشیان کرد بۆ پاککردنەوەی ئاوی کەمەند و دەستپێکردنی پێشگیری.",
    author: "نووسەر: Huda Karim",
    date: "2025-11-04",
    category: "ژینگە",
    image: environment,
  },
  {
    id: 24,
    title: "ماشیندا دەستکاریکردنی دەلى بەهوشیارییەکی باشتر",
    description: "AI بۆ وەرگرتنی قەرهەنگی دەستکاریکردن و ڕاستی زیاد کرد.",
    author: "نووسەر: Jinwoo Choi",
    date: "2025-11-03",
    category: "تێکنەلۆجی",
    image: ai,
  },
  {
    id: 25,
    title: "جەماوەری نەتەوەکان لە سەودا گەشە دەکەن",
    description: "گواستنەوەی بازرگانییەکان نێوان وڵاتان ڕەخنە کرا و چاکتر کرا.",
    author: "نووسەر: Rana Saeed",
    date: "2025-11-02",
    category: "جیهان",
    image: financial,
  },
  {
    id: 26,
    title: "ڕێنمایی خۆراک بۆ دڵنوایی و تەندروستی",
    description:
      "پێشنیارەکانی پزیشکان سەبارەی خۆراکی سەوز و ڕۆژانە بڵاوکرایەوە.",
    author: "نووسەر: Karim Nader",
    date: "2025-11-01",
    category: "تەندروستی",
    image: science,
  },
  {
    id: 27,
    title: "یاریزانان لە مۆسمی نوێ داڕشتن بکەن",
    description: "ڕاهێنانی نوێی فیتنێس بۆ تیمە وەرزشییەکان بڵاوکراوە.",
    author: "نووسەر: Naila Torres",
    date: "2025-10-31",
    category: "وەرزش",
    image: environment,
  },
  {
    id: 28,
    title: "لە بوارە ئاسمانییەکاندا تاقیکردنەوەیی نوێ",
    description: "تاقیکردنەوەیەکی ئاسمانی دەستپێکرد بۆ چاودێری کۆمێتەی دوور.",
    author: "نووسەر: Peter Novak",
    date: "2025-10-30",
    category: "زانست",
    image: ai,
  },
  {
    id: 29,
    title: "سەوزکردنی کارگێرییەکانی پیشەسازی",
    description: "کۆمپانیاکان بەرنامهی زێرین بۆ کەمکردنی پاشماوە بڵاوکردنەوە.",
    author: "نووسەر: Hana Yılmaz",
    date: "2025-10-29",
    category: "ژینگەی ژیان",
    image: financial,
  },
  {
    id: 30,
    title: "پاراستنی داتا لە ناو بانکی دیجیتال",
    description:
      "یاسای نوێ بۆ پاراستنی داتای کڕیاران لە بانەکانی ئینتەرنێت سەلماندرا.",
    author: "نووسەر: Mark Liu",
    date: "2025-10-28",
    category: "تێکنەلۆجی",
    image: science,
  },
  {
    id: 31,
    title: "بازاڕی نەوت نرخی گۆڕاوە توماربکد",
    description: "چارەسەرە نوێکان بۆ پەیوەندیی گۆڕانکاری نرخی نەوت داوا کرا.",
    author: "نووسەر: Leila Farah",
    date: "2025-10-27",
    category: "دارایی",
    image: environment,
  },
  {
    id: 32,
    title: "ڕەخنە لە بارودۆخی توێژینەوەی زانستی",
    description: "پەروەردەکاران ڕێنمایی بەرز کرا بۆ شێوەی بڵاوی زانیاری.",
    author: "نووسەر: Mustafa Bekir",
    date: "2025-10-26",
    category: "زانست",
    image: ai,
  },
  {
    id: 33,
    title: "پاراستنی ژیانی ئاژەڵان لە ناوچە گەرم",
    description:
      "پڕۆژەیەکی هاوبەش دەستپێکرد بۆ پاراستنی ئاژەڵانی مەترسی لێیانە.",
    author: "نووسەر: Rojin Ahmed",
    date: "2025-10-25",
    category: "ژینگە",
    image: financial,
  },
  {
    id: 34,
    title: "پەرەپێدانی کلاود بۆ کارگە گەورەکان",
    description: "کۆمپانیاکان سیستەمی کلاود و سێکیوریتی بەهێز کرد.",
    author: "نووسەر: Alex Morgan",
    date: "2025-10-24",
    category: "تێکنەلۆجی",
    image: science,
  },
  {
    id: 35,
    title: "گۆڤاری نێودەوڵەتی سەبارەی هاوبەشکاری",
    description: "ڕاپۆرتی نوێ سەبارەی پەیوەندیدانی دیپلۆماسی و بازاڕ بڵاوکرا.",
    author: "نووسەر: Nadia Ismail",
    date: "2025-10-23",
    category: "జیهان".replace("జ", "ج"), // ensure Sorani "جیهان"
    image: environment,
  },
  {
    id: 36,
    title: "ڕاهێنانی خوێندنی خەون بۆ خوابەرەکان",
    description: "پزیشکان دەڵێن رێژەی خەونی باشترین کاریگەر لە سەر دڵنرمییە.",
    author: "نووسەر: Sara Mohsin",
    date: "2025-10-22",
    category: "تەندروستی",
    image: ai,
  },
  {
    id: 37,
    title: "هاوبەشی وەرزشی نێوان یاریزانان",
    description: "پێشکەوتنی تاکنیکی لە یارییەکان هاوبەشی زیاد کرد.",
    author: "نووسەر: Diego Alvarez",
    date: "2025-10-21",
    category: "وەرزش",
    image: financial,
  },
  {
    id: 38,
    title: "توێژینەوەی نوێ لە فیزیا",
    description: "زانیاریی نوێ سەبارەی موجەکان لە بوارە ئاسمانییەکان بڵاوکرا.",
    author: "نووسەر: Julia Stein",
    date: "2025-10-20",
    category: "زانست",
    image: science,
  },
  {
    id: 39,
    title: "پروگرام بۆ کەمکردنی کەمەندەکان لە شار",
    description: "شارەکان بەهێزکردنی خەڵکیان بۆ پاککردنەوەی ناوخۆ دەستپێکرد.",
    author: "نووسەر: Amal Jassim",
    date: "2025-10-19",
    category: "ژینگەی ژیان",
    image: environment,
  },
  {
    id: 40,
    title: "پاراستنی سیستەمەکانی بانکی لە هێرش",
    description: "هەنگاوە نوێکان بۆ پاراستنی زانستە داتاکان دابین کرا.",
    author: "نووسەر: Victor Chen",
    date: "2025-10-18",
    category: "تێکنەلۆجی",
    image: ai,
  },
  {
    id: 41,
    title: "بازاڕی سه‌رمایە گۆڕانکارییەکی نوێ دید",
    description: "بەهۆی هەواڵی باژە و نرخەکان گۆڕانکاری هات.",
    author: "نووسەر: Zahra Alawi",
    date: "2025-10-17",
    category: "دارایی",
    image: financial,
  },
  {
    id: 42,
    title: "میکرۆبەکان و کاریگەرەکانیان لە تەندروستی",
    description: "توێژینەوە دەردەخاتەوە میکرۆبە باشەکان چۆن کاریگەرییان هەیە.",
    author: "نووسەر: Reza Kiani",
    date: "2025-10-16",
    category: "زانست",
    image: science,
  },
  {
    id: 43,
    title: "بەرنامە بۆ پاراستنی کوێستانەکان",
    description: "پڕۆژەیەکی هاوبەش بۆ پاراستنی ناوچە کوێستانی دەستپێکرا.",
    author: "نووسەر: Tara Mansour",
    date: "2025-10-15",
    category: "ژینگە",
    image: environment,
  },
  {
    id: 44,
    title: "هاوپەیمان بۆ ماشیندا ئەمنی زیاتر",
    description: "کۆمپانیاکان بەشداریکردن بۆ ئەمنی سەرهێل بەرنامەی ئەنلاین.",
    author: "نووسەر: Andre Silva",
    date: "2025-10-14",
    category: "تێکنەلۆجی",
    image: ai,
  },
  {
    id: 45,
    title: "هەواڵی دیپلۆماسیی نوێ لە ڕۆژئاوای ناوچە",
    description:
      "گفتوگۆی ئاشتییەکان دەستپێکرد بۆ باشترکردنی پەیوەندی نێوان وڵاتان.",
    author: "نووسەر: Bayan Rasul",
    date: "2025-10-13",
    category: "جیهان",
    image: financial,
  },
  {
    id: 46,
    title: "ڕێنمایی باش دەربارەی خواردنی بەهێز",
    description: "پزیشکان ڕاهێنانەکان بۆ خەیاڵی خواردن و ڕێژەی ڕۆژانە دەنوسن.",
    author: "نووسەر: Lina Haddad",
    date: "2025-10-12",
    category: "تەندروستی",
    image: science,
  },
  {
    id: 47,
    title: "تیمەکان ڕاهێنانی تاکنیکی زیاد کرد",
    description: "ڕاهێنانی نوێ بۆ کارامەیی لە یارییەکان بەکار هات.",
    author: "نووسەر: Pedro Lima",
    date: "2025-10-11",
    category: "وەرزش",
    image: environment,
  },
  {
    id: 48,
    title: "ستێرەیەکی نوێ لە کۆمەلە سەیارەکاندا دیاریکرا",
    description: "ناسا دەستکەوتێکی نوێ لە چاودێری ستێرە دیاری کرد.",
    author: "نووسەر: Elena Rossi",
    date: "2025-10-10",
    category: "زانست",
    image: ai,
  },
  {
    id: 49,
    title: "فەشەن و پاراستنی ژینگە لەسەر خەت",
    description: "پیشەسازی فەشەن پێویستە شێوازە سەوزتر بەکاربێت.",
    author: "نووسەر: Yasmin Arif",
    date: "2025-10-09",
    category: "ژینگەی ژیان",
    image: financial,
  },
  {
    id: 50,
    title: "هێرشەکانی فیشینگ و چۆنیەتی پاراستن",
    description: "ڕاهێنان بۆ ناسینەوەی ئیمەیلە هەڵە و پاراستنی کڕیاران.",
    author: "نووسەر: Tom Baker",
    date: "2025-10-08",
    category: "تێکنەلۆجی",
    image: science,
  },
  {
    id: 51,
    title: "بازاڕی زێرین بەهێزبوون توماربکد",
    description: "زێرین بە هۆی مەترسییە سیاسییەکان هەڵدەنگ بەرز کرد.",
    author: "نووسەر: Arwa Saleh",
    date: "2025-10-07",
    category: "دارایی",
    image: environment,
  },
  {
    id: 52,
    title: "ژینگەناسی و توێژینەوەیەکی تازە",
    description: "زانیارییەکی نوێ دەربارەی پەیوەندیی ژینگە و جوگرافیا بڵاوکرا.",
    author: "نووسەر: Farid Khan",
    date: "2025-10-06",
    category: "زانست",
    image: ai,
  },
  {
    id: 53,
    title: "پاراستنی دارستان بۆ کەمکردنی دیوەکردن",
    description: "پڕۆژەکان لە ناوچە گەورەکان دەستپێکردن بۆ پاراستنی دارستان.",
    author: "نووسەر: Heba Nabil",
    date: "2025-10-05",
    category: "ژینگە",
    image: financial,
  },
  {
    id: 54,
    title: "چاککردنی سێکیوریتی ناو کلاود",
    description: "ڕێنمایی بۆ پاراستنی داتای کۆمپانیایە گەورەکان.",
    author: "نووسەر: Ivan Petrov",
    date: "2025-10-04",
    category: "تێکنەلۆجی",
    image: science,
  },
  {
    id: 55,
    title: "ڕێکەوتنەکانی نێودەوڵەتی بەرز دەبن",
    description: "گفتوگۆیە سیاسییەکان کەمکردنی توندوتیژیان هەبوو.",
    author: "نووسەر: Dilan Mahmood",
    date: "2025-10-03",
    category: "جیهان",
    image: environment,
  },
  {
    id: 56,
    title: "خەریکەکان بۆ باشترکردنی ڕێژەی خەون",
    description: "ڕاهێنانەکان بۆ کەمکردنی قاوە لە ئێواران و پێشخەوتنی خەون.",
    author: "نووسەر: Mona Jalal",
    date: "2025-10-02",
    category: "تەندروستی",
    image: ai,
  },
  {
    id: 57,
    title: "پێشکەوتنی تاکنیکی لە یارییەکان",
    description: "کارگێری گۆڕانکاری لە ئامێرەکان بۆ کارامەیی یاریزانان.",
    author: "نووسەر: Ahmed Zaki",
    date: "2025-10-01",
    category: "وەرزش",
    image: financial,
  },
  {
    id: 58,
    title: "زانیاری نوێ لەسەر موجەی ئاسمانی",
    description: "خانەدانە زانستکاران دەستکەوتیان بڵاوکرد بۆ موجەکان.",
    author: "نووسەر: Chloe Martin",
    date: "2025-09-30",
    category: "زانست",
    image: science,
  },
  {
    id: 59,
    title: "کەمکردنی پاشماوە لە شارەکان",
    description:
      "ڕێنماییەکانی ژینگە بۆ ورووشتنی پاشماوە و جیاکردنەوەی مادەکان.",
    author: "نووسەر: Bahia Sami",
    date: "2025-09-29",
    category: "ژینگەی ژیان",
    image: environment,
  },
  {
    id: 60,
    title: "ڕوونکردنەوەی مەترسییە تازەکانی سایبەر",
    description:
      "هێرشەکان لەسەر پلاتفۆرمەکانی پارەدان لەناوچە جیهانی زیاد بوون.",
    author: "نووسەر: Kevin Wright",
    date: "2025-09-28",
    category: "تێکنەلۆجی",
    image: ai,
  },
  {
    id: 61,
    title: "بازاڕی هەواڵەکان سەیر گۆڕانکاری کرد",
    description: "نرخی بەرهەمەکان بە هۆی ئاگادارییەکان دەگۆڕێ.",
    author: "نووسەر: Aref Barzan",
    date: "2025-09-27",
    category: "دارایی",
    image: financial,
  },
  {
    id: 62,
    title: "کیمیای ژیان لە خۆشبەرووکاندا",
    description: "توێژینەوەی نوێ دەربارەی ڕەهەندی کیمیای ژیان بڵاوکرا.",
    author: "نووسەر: Hadi Fares",
    date: "2025-09-26",
    category: "زانست",
    image: science,
  },
  {
    id: 63,
    title: "پلان بۆ پاراستنی کەمەندەکان",
    description: "هاوبەشکاری شارەکان بۆ پاککردنەوە و پاراستنی ژینگە.",
    author: "نووسەر: Renas Ali",
    date: "2025-09-25",
    category: "ژینگە",
    image: environment,
  },
  {
    id: 64,
    title: "کەرتی دیجیتاڵ و سێکیوریتیی بەرز",
    description: "کۆمپانیاکان سیستەمەکانیان بەهێز کرد بۆ پاراستن لە هێرش.",
    author: "نووسەر: Samir Haddadi",
    date: "2025-09-24",
    category: "تێکنەلۆجی",
    image: ai,
  },
  {
    id: 65,
    title: "دیپلۆماسی ژینگەیی لە کۆڕی نێودەوڵەتی",
    description: "ڕاهێنان بۆ هاوبەشی بۆ پاراستنی ژینگەی جیهان.",
    author: "نووسەر: Shirin Kamal",
    date: "2025-09-23",
    category: "جیهان",
    image: financial,
  },
  {
    id: 66,
    title: "ڕێژەی خواردنی ویتامینەکان",
    description: "ڕێنمایی بۆ رێژەی ویتامین و مەزنەکان بۆ تەندروستی.",
    author: "نووسەر: Basel Nasser",
    date: "2025-09-22",
    category: "تەندروستی",
    image: science,
  },
  {
    id: 67,
    title: "تیمەکان لە یارییە گشتی پێشکەوتن کرد",
    description: "هاندەریکردنی تاکنیکی بۆ بردن لە یارییەکان.",
    author: "نووسەر: Katerina Ivanova",
    date: "2025-09-21",
    category: "وەرزش",
    image: environment,
  },
  {
    id: 68,
    title: "زانستکاران لەبارەی کوانتاومی باس دەکەن",
    description: "ڕوونکردنەوەی یاسای کوانتاوم بۆ خانەدانەوەکان.",
    author: "نووسەر: Tobias Meier",
    date: "2025-09-20",
    category: "زانست",
    image: ai,
  },
  {
    id: 69,
    title: "پلان بۆ کەمکردنی دابینکردنی پلاستیک",
    description: "هاوبەشکاری لە پیشەسازی بۆ مادەی سەوزتر.",
    author: "نووسەر: Eman Qassem",
    date: "2025-09-19",
    category: "ژینگەی ژیان",
    image: financial,
  },
  {
    id: 70,
    title: "پەیوەندی سێکیوریتی و کۆمپیوتەرەکان",
    description: "یاسای پاراستن بۆ کۆمپانیا و کڕیاران بەهێز کرا.",
    author: "نووسەر: Hao Zhang",
    date: "2025-09-18",
    category: "تێکنەلۆجی",
    image: science,
  },
  {
    id: 71,
    title: "بازاڕی دۆلار گۆڕانکاری کرد",
    description: "تێکڕاوەکانی نرخ بەپێی ئاگادارییەکان سارد بوون.",
    author: "نووسەر: Darya Miran",
    date: "2025-09-17",
    category: "دارایی",
    image: environment,
  },
  {
    id: 72,
    title: "توێژینەوەی نوێ لە باکتریا باشەکان",
    description: "باکتریا باشەکان لە ژینگە هەڵسوکەوتی باشان هەیە.",
    author: "نووسەر: Parviz Jalili",
    date: "2025-09-16",
    category: "زانست",
    image: ai,
  },
  {
    id: 73,
    title: "پاراستنی ڕەشنەی ژینگە لە ناوچە گەرمەکان",
    description: "ڕێنمایی سەبارەی پاراستنی ڕەشنە و ئاژەڵان.",
    author: "نووسەر: Nergiz Talib",
    date: "2025-09-15",
    category: "ژینگە",
    image: financial,
  },
  {
    id: 74,
    title: "کۆمپانیاکان بەکارهێنانی AI زیاد دەکەن",
    description: "کارگێری باشتر بۆ بەرهەم و خزمەتگوزاریەکان.",
    author: "نووسەر: George Patel",
    date: "2025-09-14",
    category: "تێکنەلۆجی",
    image: science,
  },
  {
    id: 75,
    title: "پەیوەندی نێودەوڵەتی و هاوبەشییە نوێکان",
    description: "هەنگاو بۆ گەشەی دیپلۆماسی و ئاشتیی.",
    author: "نووسەر: Zana Othman",
    date: "2025-09-13",
    category: "جیهان",
    image: environment,
  },
  {
    id: 76,
    title: "ڕێژەی پیاسە و خواردن بۆ دڵنرمی",
    description: "ڕاهێنان بۆ کەمکردنی قەند و خواردنی سەوز.",
    author: "نووسەر: Reem Basri",
    date: "2025-09-12",
    category: "تەندروستی",
    image: ai,
  },
  {
    id: 77,
    title: "پێشکەوتنی تاکنیکی لە فێتەنێس یاریزانان",
    description: "ئامێرە نوێکان بۆ ڕاهێنانی درێژخایەن.",
    author: "نووسەر: Bruno Costa",
    date: "2025-09-11",
    category: "وەرزش",
    image: financial,
  },
  {
    id: 78,
    title: "توێژینەوەیەکی نوێ لە ئەسترۆفیزیک",
    description: "ڕوونکردنەوەی تەواو بۆ گەشتە ئاسمانیەکان.",
    author: "نووسەر: Amelie Dupont",
    date: "2025-09-10",
    category: "زانست",
    image: science,
  },
  {
    id: 79,
    title: "خاوەنی ژینگە سەبارەی پلاستیک ئاگادار کرا",
    description: "پڕۆژەی ئاگاداری بۆ کەمکردنی بەکارهێنانی پلاستیک.",
    author: "نووسەر: Jwan Karim",
    date: "2025-09-09",
    category: "ژینگەی ژیان",
    image: environment,
  },
  {
    id: 80,
    title: "پاراستنی کۆمپانیاکان لە هێرشە دیژیتال",
    description: "ڕێنماییەکان بۆ فایروۆڵ و دڵنرمی داتاکان.",
    author: "نووسەر: Priya Rao",
    date: "2025-09-08",
    category: "تێکنەلۆجی",
    image: ai,
  },
  {
    id: 81,
    title: "بازاڕی سه‌ره‌مایە هاوبەشیی زیاد کرد",
    description: "کڕین و فرۆشتن بەهۆی هیوای گەشەی ئابووری بەرز بوو.",
    author: "نووسەر: Halat Mohammed",
    date: "2025-09-07",
    category: "دارایی",
    image: financial,
  },
  {
    id: 82,
    title: "ژینگەناسی کۆمەڵەی باکتریا",
    description: "پەیوەندییەکان لە نێوان باکتریا و تەندروستی روونکراوە.",
    author: "نووسەر: Yasir Dawood",
    date: "2025-09-06",
    category: "زانست",
    image: science,
  },
  {
    id: 83,
    title: "پاراستنی ژینگەی ناوچە ڕووبەری",
    description: "پڕۆژەی پاککردنەوەی ڕووبەری و پاراستنی ئاوی ڕووبار.",
    author: "نووسەر: Tara Ahmad",
    date: "2025-09-05",
    category: "ژینگە",
    image: environment,
  },
  {
    id: 84,
    title: "کەرتی کلاود و تاقیکردنەوەی سێکیوریتی",
    description: "کۆمپانیاکان تاقیکردنەوەیان کرد بۆ هێرشە دیژیتال.",
    author: "نووسەر: Luis Ortega",
    date: "2025-09-04",
    category: "تێکنەلۆجی",
    image: ai,
  },
  {
    id: 85,
    title: "گفتوگۆی ئاشتییەکانی نێودەوڵەتی بەرهەم هێنان",
    description: "هاوبەشییە نوێکان بەهێزبوون لە پەیوەندییە دیپلۆماسییەکان.",
    author: "نووسەر: Shaho Aziz",
    date: "2025-09-03",
    category: "جیهان",
    image: financial,
  },
  {
    id: 86,
    title: "ڕێنمایی بۆ ڕۆشتنی خواردنە سەوزەکان",
    description: "ڕێژەی خواردن بۆ باشکردنی دڵنرمی و توانای جەستە.",
    author: "نووسەر: Dima Saleem",
    date: "2025-09-02",
    category: "تەندروستی",
    image: science,
  },
  {
    id: 87,
    title: "یارییەکان لە مۆسمی پاییز هاوبەشی کرد",
    description: "ڕاهێنان بۆ سازکردنی تیم و سەرکەوتن.",
    author: "نووسەر: Marco Rizzo",
    date: "2025-09-01",
    category: "وەرزش",
    image: environment,
  },
  {
    id: 88,
    title: "توێژینەوەی نوێ لە کۆسمۆلۆجی",
    description: "ڕوونکردنەوەی لەبارەی پەیدابوونی کائنات.",
    author: "نووسەر: Aya Nakamura",
    date: "2025-08-31",
    category: "زانست",
    image: ai,
  },
  {
    id: 89,
    title: "پلان بۆ کەمکردنی کەمەندەکان لە فڕۆشگا",
    description: "هاوبەشکاری لەگەڵ کڕیاران بۆ جیاکردنەوەی مادەکان.",
    author: "نووسەر: Sara Younis",
    date: "2025-08-30",
    category: "ژینگەی ژیان",
    image: financial,
  },
  {
    id: 90,
    title: "سێکیوریتی دیژیتال بۆ کۆمپانیا بچووك",
    description: "ڕێنماییە سەرهێلی بۆ پاراستنی داتا و ئامێرەکان.",
    author: "نووسەر: Nikhil Mehta",
    date: "2025-08-29",
    category: "تێکنەلۆجی",
    image: science,
  },
  {
    id: 91,
    title: "بازاڕی بەرهەمە سەوزەکان بەرز بوو",
    description: "خواردنی سەوز و بەرهەمە طبیعییەکان داواکارەکان زیاد کرد.",
    author: "نووسەر: Avan Jalal",
    date: "2025-08-28",
    category: "دارایی",
    image: environment,
  },
  {
    id: 92,
    title: "توێژینەوەی ژنێتیک و کاریگەرێتییەکان",
    description: "زانیاریی نوێ سەبارەی ژنێتیک بۆ ناساندنی نەخۆشی.",
    author: "نووسەر: Bahar Karim",
    date: "2025-08-27",
    category: "زانست",
    image: ai,
  },
  {
    id: 93,
    title: "پاراستنی ژینگەی ناوچە دەریایی",
    description: "پڕۆژەی پاککردنەوەی دەریا و پاراستنی ماسی.",
    author: "نووسەر: Shilan Omer",
    date: "2025-08-26",
    category: "ژینگە",
    image: financial,
  },
  {
    id: 94,
    title: "ڕاهێنانی سێکیوریتی سەرۆکی بۆ کۆمپانیاکان",
    description: "سیستەمی پاراستن لە هێرشە دیژیتال بەرز کرا.",
    author: "نووسەر: Hyejin Park",
    date: "2025-08-25",
    category: "تێکنەلۆجی",
    image: science,
  },
  {
    id: 95,
    title: "دیپلۆماسی و هاوبەشییەکانی نێوان وڵاتان",
    description: "چەند ڕێکەوتنێکی گرنگ بۆ کەمکردنی توندوتیژی.",
    author: "نووسەر: Baran Taher",
    date: "2025-08-24",
    category: "جیهان",
    image: environment,
  },
  {
    id: 96,
    title: "ڕێژەی خواردن و ڕاهێنانی ڕۆژانە",
    description: "پێشنیارەکان بۆ خۆراکی سەوز و ڕاهێنانی نەرمی جەستە.",
    author: "نووسەر: Dorsa Vahidi",
    date: "2025-08-23",
    category: "تەندروستی",
    image: ai,
  },
  {
    id: 97,
    title: "پێشکەوتن لە یارییەکان و تاقیکردنەوەی تاکنیکی",
    description: "فێرکاری نوێ بۆ کارامەیی و بردن.",
    author: "نووسەر: Emir Kaya",
    date: "2025-08-22",
    category: "وەرزش",
    image: financial,
  },
  {
    id: 98,
    title: "توێژینەوەی نوێ لە ستێرەناسی",
    description: "پەیوەندی نێوان ستێرەکان و جوگرافیا ڕوونکرا.",
    author: "نووسەر: Hanna Schulz",
    date: "2025-08-21",
    category: "زانست",
    image: science,
  },
  {
    id: 99,
    title: "پاراستنی ژینگەی خانەوە",
    description: "ڕێنمایی بۆ کەمکردنی پاشماوە و بەکارهێنانی مادەی سەوز.",
    author: "نووسەر: Delvin Amin",
    date: "2025-08-20",
    category: "ژینگەی ژیان",
    image: environment,
  },
  {
    id: 100,
    title: "سێکیوریتی و پاراستنی داتا لە پلاتفۆرمەکان",
    description: "ڕەخنە و چارەسەر بۆ هێرشەکان لەسەر پلاتفۆرمە دیژیتال.",
    author: "نووسەر: Arman Reza",
    date: "2025-08-19",
    category: "تێکنەلۆجی",
    image: ai,
  },
];

export default api;
